services:
  reut-music-player:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: reut-music-player
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./server/work:/app/server/work

    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      YTDLP_PATH: /usr/local/bin/yt-dlp

    devices:
      - /dev/snd:/dev/snd
    
    group_add:
      - "29"

    
    
      