services:
  reut-music-player:
    build: .
    container_name: reut-music-player
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./server/work:/app/server/work

    environment:
      YTDLP_PATH: /home/pi/.local/bin/yt-dlp